name: continous intergration

on: [push, pull_request, workflow_dispatch]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: checkout code
     uses: actions/checkout@v2

   - name: install dependencies
     run: npm install

   - name: run build
     run: npm run build

 test:
  needs: [build]
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v2
     name: "Checkout repository"

   - name: install dependencies
     run: npm install

   - name: run tests
     run: npm run test --if-present
